//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAClassifieds.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAC_Country
    {
        public TAC_Country()
        {
            this.TAC_User = new HashSet<TAC_User>();
        }
    
        public int CountryId { get; set; }
        public string CountryName { get; set; }
    
        public virtual ICollection<TAC_User> TAC_User { get; set; }
    }
}
